CREATE TABLE customers (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    phone VARCHAR(50),
    customer_type VARCHAR(20) NOT NULL DEFAULT 'RETAIL',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);